<?php

namespace Networkrailbusinesssystems\SupportPage\Providers;

use Illuminate\Support\ServiceProvider;

class SupportPageProvider extends ServiceProvider
{
    public function register(): void
    {
        parent::register(); // TODO: Change the autogenerated stub

        //before the program starts up
    }

    public function boot(): void
    {
        $this->bootRoutes();
        $this->bootViews();

    }

    protected function bootRoutes(): void
    {
        //ADD ROUTES

    }

    protected function bootViews(): void
    {
        $this->loadViewsFrom(
            __DIR__.'/../../resources/views',
            'support-page'
        );
    }
}
